Use another reporter

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -28,10 +28,9 @@ jobs:
     - name: Build
       run: mvn -DskipTests package
     - name: Test
-      run: mvn -Dmaven.test.failure.ignore=true test
+      run: mvn test
     - name: Attach test report
-      uses: dorny/test-reporter@v1
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
       with:
-        name: Maven Tests
-        path: target/surefire-reports/*.xml
-        fail-on-error: true
+        report_paths: '**/target/surefire-reports/*.xml'
